### ISSUE TITLE
记面试。

### ISSUE THREAD

**Issue by xierenyuan** [xierenyuan/blog#4]
又到一年春暖花开时，然而我却即将面临失业。人生如此悲剧！
    记录一下去某团答的不好的面试题。
     
# 问题1：从输入URL到页面加载完成的过程中都发生了什么事情？

> 当时回答的时候有点懵,大致 把流程说了一遍，但是面试官，又接着追问更细致的 没有答上来。大概思路是这样的。
```
输入地址
浏览器查找域名的 IP 地址
这一步包括 DNS 具体的查找过程，包括：浏览器缓存->系统缓存->路由器缓存...
浏览器向 web 服务器发送一个 HTTP 请求
服务器的永久重定向响应（从 http://example.com 到 http://www.example.com）
浏览器跟踪重定向地址
服务器处理请求
服务器返回一个 HTTP 响应
浏览器显示 HTML
浏览器发送请求获取嵌入在 HTML 中的资源（如图片、音频、视频、CSS、JS等等）
浏览器发送异步请求
```
> 网上搜索了一篇比较系统的 留着 之后看 http://www.jianshu.com/p/e141d1543143

## 追问 服务器 是如何和浏览器交互的？
> 当时有点懵逼。 没有表述出来。当时面试给的提示的 协议 猜想 后来回来搜了下 可能是如下的答案。不知对不对 待考证

```
为了准确无误地把数据送达目标处，TCP协议采用了三次握手策略。用TCP协议把数据包送出去后，TCP不会对传送 后的情况置之不理，它一定会向对方确认是否成功送达。握手过程中使用了TCP的标志：SYN和ACK。

发送端首先发送一个带SYN标志的数据包给对方。接收端收到后，回传一个带有SYN/ACK标志的数据包以示传达确认信息。 最后，发送端再回传一个带ACK标志的数据包，代表“握手”结束。 若在握手过程中某个阶段莫名中断，TCP协议会再次以相同的顺序发送相同的数据包。

断开一个TCP连接则需要“四次握手”：
第一次挥手：主动关闭方发送一个FIN，用来关闭主动方到被动关闭方的数据传送，也就是主动关闭方告诉被动关闭方：我已经不 会再给你发数据了(当然，在fin包之前发送出去的数据，如果没有收到对应的ack确认报文，主动关闭方依然会重发这些数据)，但是，此时主动关闭方还可 以接受数据。

第二次挥手：被动关闭方收到FIN包后，发送一个ACK给对方，确认序号为收到序号+1（与SYN相同，一个FIN占用一个序号）。

第三次挥手：被动关闭方发送一个FIN，用来关闭被动关闭方到主动关闭方的数据传送，也就是告诉主动关闭方，我的数据也发送完了，不会再给你发数据了。

第四次挥手：主动关闭方收到FIN后，发送一个ACK给被动关闭方，确认序号为收到序号+1，至此，完成四次挥手。
```  

## 面试官继续追问 渲染 link style 样式加载 会阻塞渲染吗？
> 😓 当时瞬间懵逼 知道javascript 阻塞 渲染，当时回答的是阻塞  （当时想的是  FOUC（无样式内容闪烁 ） 但是其实解决无样式内容闪烁  解决的方案就是放在header 里面  不使用import 等 所以不知 是否答对） 更新答案 其实不会阻塞 

## 接着问 你知道http 状态吗 有哪些吗。
> 回答呢几个常用的
```
200
301
404
500
```
> -.- 结果 面试官 直接追问 那你知道 301  302 304  500 501 502的区别吗？  一脸懵逼 。挨基础啊 看来的好好的看书。 贴一下网上搜索的答案。别的没有去找 其实一般 知道 上面几个就够用呢 毕竟实在不知道 开发的时候遇到搜索一下就知道呢，大概面试官希望基础好的吧。😭

```
 100  Continue  继续，一般在发送post请求时，已发送了http header之后服务端将返回此信息，表示确认，之后发送具体参数信息

    200  OK   正常返回信息

    201  Created  请求成功并且服务器创建了新的资源

    202  Accepted  服务器已接受请求，但尚未处理

    301  Moved Permanently  请求的网页已永久移动到新位置。

    302 Found  临时性重定向。

    303 See Other  临时性重定向，且总是使用 GET 请求新的 URI。

    304  Not Modified  自从上次请求后，请求的网页未修改过。


    400 Bad Request  服务器无法理解请求的格式，客户端不应当尝试再次使用相同的内容发起请求。

    401 Unauthorized  请求未授权。

    403 Forbidden  禁止访问。

    404 Not Found  找不到如何与 URI 相匹配的资源。

    500 Internal Server Error  最常见的服务器端错误。

    503 Service Unavailable 服务器端暂时无法处理请求（可能是过载或维护）。
```

# 问题2  css实现三栏布局
> 可能当时太过于紧张...(＞﹏＜)。 毕竟是手写css..   写了一种方案 不是特别的理想吧 下边记录下。
```css
/*方法一：自身浮动法。左栏左浮动，右栏右浮动。*/

<style type='text/css'>
.left , .right{
            height: 300px;
            width: 200px;
        }
        .right{
            float: right;
            background-color: red;
        }
        .left{
            float: left;
            background-color: #080808;
        }
        .middle{
            height: 300px;
            margin: 0 200px;//没有这行，当宽度缩小到一定程度的时候，中间的内容可能换行
            background-color: blue;
        }
</style>




<!-- 方法二：margin负值法 -->

<style type="text/css">
            body{
                margin: 0;
                padding: 0;
            }
            .left , .right{
                height: 300px;
                width: 200px;
                float: left;
            }
            .right{
                margin-left: -200px;
                background-color: red;
            }
            .left{
                margin-left: -100%;
                background-color: #080808;
            }
            .middle{
                height: 300px;
                width: 100%;
                float: left;
                background-color: blue;
            }
</style>



    <!--放第一行-->

    <div class="middle">middle</div>

    <div class="left">left</div>

    <div class="right">right</div>





<!-- 方法三：绝对定位法。左右两栏采用绝对定位，分别固定于页面的左右两侧，中间的主体栏用左右margin值撑开距离。 -->



<style>
    body{
        margin: 0;
        padding: 0;
    }
    .left , .right{
        top: 0;
        height: 300px;
        width: 200px;
        position: absolute;
    }
    .right{
        right: 0;
        background-color: red;
    }
    .left{
        left: 0;
        background-color: #080808;
    }
    .middle{
        margin: 0 200px;
        height: 300px;
        background-color: blue;
    }
</style>


<div class="left">left</div>

<!--这种方法没有严格限定中间这栏放置何处-->

<div class="middle">middle</div>

<div class="right">right</div>

```

# 问题是  事件。
> 大概是下面的这样的题目  当点击li 时 alert 出 li 的 文本
```html
<ul id="ul">
    <li>123</li>
    <li>123</li>
    <li>123</li>
    <li>123</li>
    * 1000行
</ul>
```
> -。-。。当时逗B 呢  当时一想 就写了     document.querySelectorAll('ul li') ..这就尴尬呢。。。自从用上了框架 挨 害人不浅啊。
> 其实应该是 写事件委托吧。。
```
document.getElementById("ul").addEventListener("click",function(e) {
  // 检查事件源e.targe是否为Li
  if(e.target && e.target.nodeName.toUpperCase == "LI") {
    ...
  }
});
```  
## 追问 自定义事件如何实现 观察者模式 等等
> 我答实现的方式呢，木有答原理 被面试官鄙视呢。估计他更想知道的是原理吧。。

#  关于上下问的
> 题目大概是这个样子的
```javascript
var a=1;
var obj={
     f1=function(){
        console.log(this.a);
    },
   a:15
}
obj.f1();
obj.f1=obj.f1();
var b=obj.f1();
b();
```
> 回答 输出的值 我答的是15  15 15.  这里忽略呢 obj.f1 被重新赋值呢。。不过面试官指出 说我就答对一个。。。。让我回来试试 估计是临时出的题 他以没有搞清楚吧。。

# 关于闭包
> -。-。。。各种原因很少使用闭包 属于理论派 回答呢 可以通过闭包访问 私有变量。
> 这解释呢 最近一直在用es6 什么的很少关注这种写法呢，面试官看看呢 我写的es6的代码最后 说呢句，那es6 最终不还的转成es5  
```
  function a(){
     var b=1;
  return function (){
  console.log(b);
}
}
```  

# 算法题
> 题目大概是这样子的 两个数组 以知 数组1,数组2 的是依次递增 现在需要合成一个数组 按顺序输出，只能使用一个循环 然后我自己懵逼呢 一直想一个循环咋写。。没有考虑递归什么的估计那时候 面的 有点糟糕吧。回家重新写了一篇 大概是下面的写法 不知道是不是最优  

```javascript
  /*
         * [1,2,45,77,88,99]
         * [3,7,8]
         * 输出 [1,2,3,7,8,45,77,88,99]
         */
        var a = [1, 3, 7, 8, 21, 22, 23, 25];
        var b = [2, 6, 8, 9, 23, 24];
        var nArr = [];

        function f(arrA, arrb) {
            var lenA = arrA.length;
            var lenB = arrb.length;
            if (lenA == 0 && lenB > 0) {
                nArr = nArr.concat(arrb);
            }
            if (lenB == 0 && lenA > 0) {
                nArr = nArr.concat(arrA);
            }
            if (lenA == 0 || lenB == 0) {
                return;
            }
            arrA.forEach(function(item, index) {
                if (item < arrb[index]) {
                    nArr.push(item);
                    arrA.splice(index, 1);
                    f(arrA, arrb);
                } else {
                    nArr.push(arrb[index]);
                    arrb.splice(index, 1);
                    f(arrA, arrb);
                }
            });
        }
        f(a, b);
        console.log(nArr);
```

# 最后总结。感谢面试小哥。 😌 要多看书 多看面试题 加油！！！
